//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:3.1.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace stj1_gorev_atama_sureci.Entities {
    
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1")]
    public class E_stj1_gorev_atama_sureci_Form1Entity : FormEntity<E_stj1_gorev_atama_sureci_Form1Entity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _gorevYuzde;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _endDate;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _kalanSuresi;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _startDate;
        
        private Bimser.Framework.Domain.DataField<string> _amirAd;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _NumberOran;
        
        private E_stj1_gorev_atama_sureci_Form1VREntity _VersionEntity;
        
        private RDEntityCollection<E_stj1_gorev_atama_sureci_Form1RDEntity, E_stj1_gorev_atama_sureci_Form1RDMLEntity> _RD;
        
        private RDCEntityCollection<E_stj1_gorev_atama_sureci_Form1RDCEntity, E_stj1_gorev_atama_sureci_Form1RDCMLEntity> _RDC;
        
        private MLEntityCollection<E_stj1_gorev_atama_sureci_Form1MLEntity> _ML;
        
        private SLEntityCollection<E_stj1_gorev_atama_sureci_Form1SLEntity, E_stj1_gorev_atama_sureci_Form1SLMLEntity> _SL;
        
        private GridEntityCollection<E_stj1_gorev_atama_sureci_Form1_asamaTabloEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloMLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLMLEntity> _E_stj1_gorev_atama_sureci_Form1_asamaTablo;
        
        public E_stj1_gorev_atama_sureci_Form1Entity() {
            this.ML = new MLEntityCollection<E_stj1_gorev_atama_sureci_Form1MLEntity>();
            this.VersionEntity = new E_stj1_gorev_atama_sureci_Form1VREntity();
            this.RD = new RDEntityCollection<E_stj1_gorev_atama_sureci_Form1RDEntity, E_stj1_gorev_atama_sureci_Form1RDMLEntity>();
            this.RDC = new RDCEntityCollection<E_stj1_gorev_atama_sureci_Form1RDCEntity, E_stj1_gorev_atama_sureci_Form1RDCMLEntity>();
            this.E_stj1_gorev_atama_sureci_Form1_asamaTablo = new GridEntityCollection<E_stj1_gorev_atama_sureci_Form1_asamaTabloEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloMLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLMLEntity>();
            this.E_stj1_gorev_atama_sureci_Form1_asamaTablo.MLEntityEnabled = true;
            this.E_stj1_gorev_atama_sureci_Form1_asamaTablo.SLEntityEnabled = false;
            this.SL = new SLEntityCollection<E_stj1_gorev_atama_sureci_Form1SLEntity, E_stj1_gorev_atama_sureci_Form1SLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="gorevYuzde", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> gorevYuzde {
            get {
                return this._gorevYuzde;
            }
            set {
                this._gorevYuzde = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="endDate", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> endDate {
            get {
                return this._endDate;
            }
            set {
                this._endDate = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="kalanSuresi", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> kalanSuresi {
            get {
                return this._kalanSuresi;
            }
            set {
                this._kalanSuresi = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="startDate", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> startDate {
            get {
                return this._startDate;
            }
            set {
                this._startDate = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="amirAd", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> amirAd {
            get {
                return this._amirAd;
            }
            set {
                this._amirAd = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="NumberOran", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> NumberOran {
            get {
                return this._NumberOran;
            }
            set {
                this._NumberOran = value;
            }
        }
        
        public E_stj1_gorev_atama_sureci_Form1VREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_stj1_gorev_atama_sureci_Form1RDEntity, E_stj1_gorev_atama_sureci_Form1RDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_stj1_gorev_atama_sureci_Form1RDCEntity, E_stj1_gorev_atama_sureci_Form1RDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_stj1_gorev_atama_sureci_Form1MLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_stj1_gorev_atama_sureci_Form1SLEntity, E_stj1_gorev_atama_sureci_Form1SLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
        
        public GridEntityCollection<E_stj1_gorev_atama_sureci_Form1_asamaTabloEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloMLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLMLEntity> E_stj1_gorev_atama_sureci_Form1_asamaTablo {
            get {
                return this._E_stj1_gorev_atama_sureci_Form1_asamaTablo;
            }
            set {
                this._E_stj1_gorev_atama_sureci_Form1_asamaTablo = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1ML")]
    public class E_stj1_gorev_atama_sureci_Form1MLEntity : MLEntity<E_stj1_gorev_atama_sureci_Form1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _gorevTanim;
        
        private Bimser.Framework.Domain.DataField<string> _gorevAd;
        
        [ColumnOptionsAttribute(Name="gorevTanim", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> gorevTanim {
            get {
                return this._gorevTanim;
            }
            set {
                this._gorevTanim = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="gorevAd", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> gorevAd {
            get {
                return this._gorevAd;
            }
            set {
                this._gorevAd = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1SL")]
    public class E_stj1_gorev_atama_sureci_Form1SLEntity : SLEntity<E_stj1_gorev_atama_sureci_Form1SLEntity, E_stj1_gorev_atama_sureci_Form1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1SLML")]
    public class E_stj1_gorev_atama_sureci_Form1SLMLEntity : SLMLEntity<E_stj1_gorev_atama_sureci_Form1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1_asamaTablo")]
    public class E_stj1_gorev_atama_sureci_Form1_asamaTabloEntity : GridEntity<E_stj1_gorev_atama_sureci_Form1_asamaTabloEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloMLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _IdAsama;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _tarihAsama2;
        
        public E_stj1_gorev_atama_sureci_Form1_asamaTabloEntity() {
        }
        
        [ColumnOptionsAttribute(Name="IdAsama", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> IdAsama {
            get {
                return this._IdAsama;
            }
            set {
                this._IdAsama = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tarihAsama2", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> tarihAsama2 {
            get {
                return this._tarihAsama2;
            }
            set {
                this._tarihAsama2 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1_asamaTabloML")]
    public class E_stj1_gorev_atama_sureci_Form1_asamaTabloMLEntity : GridMLEntity<E_stj1_gorev_atama_sureci_Form1_asamaTabloMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _yuzdeAsama2;
        
        private Bimser.Framework.Domain.DataField<string> _yorumAsama;
        
        [ColumnOptionsAttribute(Name="yuzdeAsama2", Mandatory=false, Size=19)]
        public Bimser.Framework.Domain.DataField<string> yuzdeAsama2 {
            get {
                return this._yuzdeAsama2;
            }
            set {
                this._yuzdeAsama2 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="yorumAsama", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> yorumAsama {
            get {
                return this._yorumAsama;
            }
            set {
                this._yorumAsama = value;
            }
        }
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1_asamaTabloSL")]
    public class E_stj1_gorev_atama_sureci_Form1_asamaTabloSLEntity : GridSLEntity<E_stj1_gorev_atama_sureci_Form1_asamaTabloSLEntity, E_stj1_gorev_atama_sureci_Form1_asamaTabloSLMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1_asamaTabloSLML")]
    public class E_stj1_gorev_atama_sureci_Form1_asamaTabloSLMLEntity : GridSLMLEntity<E_stj1_gorev_atama_sureci_Form1_asamaTabloSLMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1VR")]
    public class E_stj1_gorev_atama_sureci_Form1VREntity : VersionEntity<E_stj1_gorev_atama_sureci_Form1VREntity> {
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1RDC")]
    public class E_stj1_gorev_atama_sureci_Form1RDCEntity : RDCEntity<E_stj1_gorev_atama_sureci_Form1RDCEntity, E_stj1_gorev_atama_sureci_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1RDCML")]
    public class E_stj1_gorev_atama_sureci_Form1RDCMLEntity : RDCMLEntity<E_stj1_gorev_atama_sureci_Form1RDCMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1RD")]
    public class E_stj1_gorev_atama_sureci_Form1RDEntity : RDEntity<E_stj1_gorev_atama_sureci_Form1RDEntity, E_stj1_gorev_atama_sureci_Form1RDMLEntity> {
    }
    
    [TableOptions(TableName="E_stj1_gorev_atama_sureci_Form1RDML")]
    public class E_stj1_gorev_atama_sureci_Form1RDMLEntity : RDMLEntity<E_stj1_gorev_atama_sureci_Form1RDMLEntity> {
    }
}




